name: Setup Podman Compose
description: Set up your GitHub Actions workflow with a latest stable podman-compose


branding:
  icon: file-text
  color: green

runs:
  using: "composite"
  steps:
    - name: Install podman-compose from ubuntu repositories
      run: pip3 install podman-compose
      shell: bash
