name: Setup Podman Compose

branding:
  icon: file-text
  color: green

runs:
  using: "composite"
  steps:
    - name: Install podman-compose from ubuntu repositories
      run: pip3 install podman-compose
      shell: bash
